// Mirrored from eduhire-backend/src/shared/enums/index.ts — BE is source of truth

export enum Role {
  TEACHER = 'TEACHER',
  RECRUITER = 'RECRUITER',
  ADMIN = 'ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
  PREFER_NOT_TO_SAY = 'PREFER_NOT_TO_SAY',
}

export enum Availability {
  IMMEDIATE = 'IMMEDIATE',
  WITHIN_2_WEEKS = 'WITHIN_2_WEEKS',
  WITHIN_1_MONTH = 'WITHIN_1_MONTH',
  READY_TO_SERVE_NOTICE = 'READY_TO_SERVE_NOTICE',
  NOT_LOOKING = 'NOT_LOOKING',
}

export enum JobStatus {
  ACTIVE = 'ACTIVE',
  FILLED = 'FILLED',
  EXPIRED = 'EXPIRED',
  AUTO_DISABLED = 'AUTO_DISABLED',
  DISABLED_BY_ADMIN = 'DISABLED_BY_ADMIN',
}

export enum ApplicationState {
  INTERESTED = 'INTERESTED',
  SHORTLISTED = 'SHORTLISTED',
  PAID = 'PAID',
  WON = 'WON',
  CLOSED = 'CLOSED',
}

export enum PaymentKind {
  APPLICATION = 'APPLICATION',
  SUBSCRIPTION = 'SUBSCRIPTION',
  BOOST = 'BOOST',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum SubscriptionStatus {
  ACTIVE = 'ACTIVE',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum NotificationKind {
  APPLICATION_SHORTLISTED = 'APPLICATION_SHORTLISTED',
  APPLICATION_WON = 'APPLICATION_WON',
  APPLICATION_CLOSED = 'APPLICATION_CLOSED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  NEW_JOB_IN_LOCATION = 'NEW_JOB_IN_LOCATION',
  NEW_INTEREST = 'NEW_INTEREST',
  APPLICANT_PAID = 'APPLICANT_PAID',
  JOB_FILLED = 'JOB_FILLED',
  JOB_EXPIRING_SOON = 'JOB_EXPIRING_SOON',
  JOB_AUTO_DISABLED = 'JOB_AUTO_DISABLED',
  SUB_RENEWED = 'SUB_RENEWED',
  SUB_RENEWAL_FAILED = 'SUB_RENEWAL_FAILED',
  SCHOOL_VERIFIED = 'SCHOOL_VERIFIED',
  SCHOOL_REGISTERED = 'SCHOOL_REGISTERED',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
}

export enum UploadKind {
  RESUME = 'resume',
  LOGO = 'logo',
  CERTIFICATE = 'certificate',
  DOCUMENT = 'document',
  SCHOOL_PHOTO = 'school_photo',
  INTRO_VIDEO = 'intro_video',
}

export enum MaritalStatus {
  SINGLE = 'SINGLE',
  MARRIED = 'MARRIED',
  DIVORCED = 'DIVORCED',
  WIDOWED = 'WIDOWED',
  PREFER_NOT_TO_SAY = 'PREFER_NOT_TO_SAY',
}

export enum TypeOfPractice {
  FREELANCE = 'FREELANCE',
  REGULAR_JOB = 'REGULAR_JOB',
  PRIVATE = 'PRIVATE',
}

export enum Academics {
  INTERNSHIP          = 'INTERNSHIP',
  GRADUATE            = 'GRADUATE',
  POST_GRADUATE       = 'POST_GRADUATE',
  ASST_PROFESSOR      = 'ASST_PROFESSOR',
  ASSOCIATE_PROFESSOR = 'ASSOCIATE_PROFESSOR',
  PROFESSOR           = 'PROFESSOR',
}

export enum SalaryRange {
  BELOW_25K     = 'BELOW_25K',
  RANGE_25_50K  = 'RANGE_25_50K',
  RANGE_50K_1L  = 'RANGE_50K_1L',
  RANGE_1L_1_5L = 'RANGE_1L_1_5L',
  RANGE_1_5L_2L = 'RANGE_1_5L_2L',
  ABOVE_2L      = 'ABOVE_2L',
}

export enum Subject {
  PRIMARY                = 'PRIMARY',
  ENGLISH                = 'ENGLISH',
  MATHEMATICS            = 'MATHEMATICS',
  SCIENCE                = 'SCIENCE',
  PHYSICS                = 'PHYSICS',
  CHEMISTRY              = 'CHEMISTRY',
  BIOLOGY                = 'BIOLOGY',
  SOCIAL_STUDIES         = 'SOCIAL_STUDIES',
  HINDI                  = 'HINDI',
  COMPUTER_SCIENCE       = 'COMPUTER_SCIENCE',
  TELUGU                 = 'TELUGU',
  HISTORY                = 'HISTORY',
  GEOGRAPHY              = 'GEOGRAPHY',
  ECONOMICS              = 'ECONOMICS',
  BUSINESS_STUDIES       = 'BUSINESS_STUDIES',
  ACCOUNTANCY            = 'ACCOUNTANCY',
  INFORMATION_TECHNOLOGY = 'INFORMATION_TECHNOLOGY',
  ART_CRAFTS             = 'ART_CRAFTS',
  MUSIC                  = 'MUSIC',
  DANCE                  = 'DANCE',
  ENVIRONMENTAL_SCIENCE  = 'ENVIRONMENTAL_SCIENCE',
  PRE_PRIMARY_EDUCATION  = 'PRE_PRIMARY_EDUCATION',
  SPECIAL_EDUCATION      = 'SPECIAL_EDUCATION',
  SCHOOL_ADMINISTRATION  = 'SCHOOL_ADMINISTRATION',
  COUNSELING             = 'COUNSELING',
  OTHERS                 = 'OTHERS',
}

export enum TeacherPost {
  SGT                 = 'SGT',
  TGT                 = 'TGT',
  PGT                 = 'PGT',
  PRE_PRIMARY_TEACHER = 'PRE_PRIMARY_TEACHER',
  HM                  = 'HM',
  PRINCIPAL           = 'PRINCIPAL',
  VICE_PRINCIPAL      = 'VICE_PRINCIPAL',
  SPECIAL_EDUCATOR    = 'SPECIAL_EDUCATOR',
  LAB_ASSISTANT       = 'LAB_ASSISTANT',
  LIBRARIAN           = 'LIBRARIAN',
  COUNSELOR           = 'COUNSELOR',
  IIT_JEE_FACULTY     = 'IIT_JEE_FACULTY',
  NEET_FACULTY        = 'NEET_FACULTY',
  OTHER               = 'OTHER',
}

export enum JobDepartment {
  PRE_PRIMARY        = 'PRE_PRIMARY',
  PRIMARY            = 'PRIMARY',
  SECONDARY          = 'SECONDARY',
  SENIOR_SECONDARY   = 'SENIOR_SECONDARY',
  ARTS_CRAFTS        = 'ARTS_CRAFTS',
  COMPUTER_SCIENCE   = 'COMPUTER_SCIENCE',
  PHYSICAL_EDUCATION = 'PHYSICAL_EDUCATION',
  ADMINISTRATION     = 'ADMINISTRATION',
  LIBRARY            = 'LIBRARY',
  COUNSELING         = 'COUNSELING',
  OTHER              = 'OTHER',
}

export enum AvailableTimings {
  TWENTY_FOUR_SEVEN = '24_7',
  MORNING = 'MORNING',
  NIGHT = 'NIGHT',
  NINE_TO_FIVE = '9_TO_5',
  EVENING = 'EVENING',
}
